### ISSUE TITLE
Add Class to Ingest Emails from the Gmail API & Store in a Vector Database Format

### ISSUE THREAD

**Issue by tmichaeldb** [mindsdb/email_rag#3]
Currently, we can ingest files, chunk them, and store them as documents in a vector database. However, we have no way to ingest data from a database or API.

We need a way to ingest emails, preprocess them, split & chunk them, and store them as documents in a vector database. We need to be mindful of exactly how we're splitting & chunking text, and which metadata information we should store for good retrieval performance.

See [email_handler](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/email_handler) in the main repo as a starting point.

Note: This issue does not cover a pipeline to continuously update with new emails. That's tracked separately.

**Comment by dusvyat** [comment]
@tmichaeldb - Let's store emails in postgres, It would be cool to try using pgvector so we can try it out with:

https://github.com/mindsdb/email_rag/blob/e25b4c10f05a90564ae737d886e27f74e126d87b/retrievers/retrievers.py#L153
